<a href="https://colab.research.google.com/github/kulvirk/-Python-problems-and-solution/blob/master/flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install flatten_json

In [7]:
import http.client
import csv
from flatten_json import flatten
import json
import pandas as pd

conn = http.client.HTTPSConnection("api-football-v1.p.rapidapi.com")

headers = {
    'x-rapidapi-host': "api-football-v1.p.rapidapi.com",
    'x-rapidapi-key': "3f7565a41amsh6dcecbe6f25bb00p1f0901jsnfb07c8807ba2"
    }

conn.request("GET", "/v2/players/fixture/168111", headers=headers)

data = (conn.getresponse()).read()
sstat2 = json.loads(data.decode("utf-8"))
data1=sstat2['api']['players']
column_list=list(flatten(data1[0]).keys()) 
df_players=pd.DataFrame(columns=column_list)
for x in data1:
    df_players=df_players.append([flatten(x)], ignore_index=True)
print(df_players.head())

  event_id    updateAt player_id  ... penalty_success penalty_missed penalty_saved
0   168111  1589382096     19258  ...               0              0             0
1   168111  1589382096     20297  ...               0              0             0
2   168111  1589382096     17775  ...               0              0             0
3   168111  1589382096     20288  ...               0              0             0
4   168111  1589382096     19892  ...               0              0             0

[5 rows x 39 columns]

In [6]:
df_players

   event_id    updateAt player_id  ... penalty_success penalty_missed penalty_saved
0    168111  1589382096     19258  ...               0              0             0
1    168111  1589382096     20297  ...               0              0             0
2    168111  1589382096     17775  ...               0              0             0
3    168111  1589382096     20288  ...               0              0             0
4    168111  1589382096     19892  ...               0              0             0
5    168111  1589382096     20305  ...               0              0             0
6    168111  1589382096     20303  ...               0              0             0
7    168111  1589382096     20290  ...               0              0             0
8    168111  1589382096     20318  ...               0              0             0
9    168111  1589382096     19774  ...               0              0             0
10   168111  1589382096     20300  ...               0              0             0
11   168111  1589382096     44900  ...               0              0             0
12   168111  1589382096     19080  ...               0              0             0
13   168111  1589382096     20314  ...               0              0             0
14   168111  1589382096     19977  ...               0              0             0
15   168111  1589382096     19911  ...               0              0             0
16   168111  1589382096     19992  ...               0              0             0
17   168111  1589382096     19581  ...               0              0             0
18   168111  1589382096     19888  ...               0              0             0
19   168111  1589382096     20436  ...               0              0             0
20   168111  1589382096     19912  ...               0              0             0
21   168111  1589382096     19913  ...               0              0             0
22   168111  1589382096     19916  ...               0              0             0
23   168111  1589382096     19907  ...               0              0             0
24   168111  1589382096     19915  ...               0              0             0
25   168111  1589382096     19880  ...               0              0             0
26   168111  1589382096     19906  ...               0              0             0
27   168111  1589382096     44853  ...               0              0             0

[28 rows x 39 columns]

In [171]:
import pandas as pd
from flatten_json import flatten 
df = pd.DataFrame(columns=column_list)
#print(data1)
data ={'event_id': 168111, 'updateAt': 1589382096, 'player_id': 19258, 'player_name': "Max O'Leary", 'team_id': 1352, 'team_name': 'Shrewsbury', 'number': 25, 'position': 'G', 'rating': '7.1', 'minutes_played': 90, 'captain': 'False', 'substitute': 'False', 'offsides': None, 'shots': {'total': 0, 'on': 0}, 'goals': {'total': 0, 'conceded': 0, 'assists': 0, 'saves': 2}, 'passes': {'total': 7, 'key': 0, 'accuracy': 21}, 'tackles': {'total': 0, 'blocks': 0, 'interceptions': 0}, 'duels': {'total': 0, 'won': 0}, 'dribbles': {'attempts': 0, 'success': 0, 'past': 0}, 'fouls': {'drawn': 0, 'committed': 0}, 'cards': {'yellow': 0, 'red': 0}, 'penalty': {'won': 0, 'commited': 0, 'success': 0, 'missed': 0, 'saved': 0}}
data=flatten(data)
print(data)
df_players=df_players.append([data],ignore_index=True,sort=False)

{'event_id': 168111, 'updateAt': 1589382096, 'player_id': 19258, 'player_name': "Max O'Leary", 'team_id': 1352, 'team_name': 'Shrewsbury', 'number': 25, 'position': 'G', 'rating': '7.1', 'minutes_played': 90, 'captain': 'False', 'substitute': 'False', 'offsides': None, 'shots_total': 0, 'shots_on': 0, 'goals_total': 0, 'goals_conceded': 0, 'goals_assists': 0, 'goals_saves': 2, 'passes_total': 7, 'passes_key': 0, 'passes_accuracy': 21, 'tackles_total': 0, 'tackles_blocks': 0, 'tackles_interceptions': 0, 'duels_total': 0, 'duels_won': 0, 'dribbles_attempts': 0, 'dribbles_success': 0, 'dribbles_past': 0, 'fouls_drawn': 0, 'fouls_committed': 0, 'cards_yellow': 0, 'cards_red': 0, 'penalty_won': 0, 'penalty_commited': 0, 'penalty_success': 0, 'penalty_missed': 0, 'penalty_saved': 0}